
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: mydoctest-web:1.0
    ports:
      - "8082:8080"
    environment:
      - ENV=production
    networks:
      - test_network
  web-db:
    image: postgres:16
    container_name: test-pg-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "8084:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - test_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8083:80"
    networks:
      - test_network
    depends_on:
      - web-db

networks:
  test_network:
    driver: bridge
volumes:
  pgdata: